### ISSUE TITLE
will not build

### ISSUE THREAD

**Issue by ghost** [DiUS/pact-provider-verifier-docker#11]
Here is the error im getting when I run docker-compose -f .\Verify_compose.yml up

Attaching to brokerimage_pactverifier_1
pactverifier_1  | /usr/local/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': Could not find 'bundler' (2.0.1) required by your /app/Gemfile.lock. (Gem::GemNotFoundException)
pactverifier_1  | To update to the latest version installed on your system, run `bundle update --bundler`.
pactverifier_1  | To install the missing version, run `gem install bundler:2.0.1`
pactverifier_1  |       from /usr/local/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
pactverifier_1  |       from /usr/local/bundle/bin/bundle:23:in `<main>'
brokerimage_pactverifier_1 exited with code 1

**Comment by dygcao** [comment]
Hi @lcpautotester, 

I created a PR for a potential fix for this issue:
https://github.com/DiUS/pact-provider-verifier-docker/pull/12.

Hope this could help. 

dygcao
